---
- name: Fixa DNS på webserver
  copy:
    content: "nameserver 8.8.8.8\n"
    dest: /etc/resolv.conf

- name: Installera Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Starta och aktivera Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Skapa enkel testsida
  copy:
    content: |
      <html>
        <body>
          <h1>Webbserver - Double-homed firewall projekt</h1>
        </body>
      </html>
    dest: /var/www/html/index.html

- name: Installera Python3 och psycopg2
  apt:
    name:
      - python3-pip
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Lägg till route till client-nät
  command: ip route add 10.0.1.0/24 via 10.0.4.1
  ignore_errors: yes
  changed_when: false

- name: Lägg till route till databas-nät
  command: ip route add 10.0.3.0/24 via 10.0.4.1
  ignore_errors: yes
  changed_when: false